spring.application.name=resume_backend
server.port=8080
google.gemini.api_key="AIzaSyBmMmwoBFsJtKQOHIM8krt1AjioLE74JF4"
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
